import type { Metadata } from "next";
import "./globals.css";
// Supports weights 100-700
import '@fontsource-variable/roboto-mono';
// Supports weights 100-900
import '@fontsource-variable/inter';


export const metadata: Metadata = {
  title: "TechNow",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
